stages:
  - build
  - deploy
build:
  stage: build
  script:
  - echo "Building the app"
  - docker build akagilnc/trade-io-tool .
deploy_staiging:
  stage: deploy
  only:
  - master
  script:
  - echo "Deploying the app"
  - docker push akagilnc/trade-io-tool