image: docker:18

stages:
  - build
  - push

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
  - echo "Building the app"
  - docker build akagilnc/trade-io-tool .
push:
  stage: push
  only:
  - master
  script:
  - echo "Deploying the app"
  - docker push akagilnc/trade-io-tool