language: python

services:
  - docker

before_install:
  - docker build -t akagilnc/trade-io-tool .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push akagilnc/trade-io-tool