# Generated by Django 2.2.4 on 2019-08-24 06:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='待提交', max_length=50)),
                ('SKU', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200, verbose_name='标题英文')),
                ('title_cn', models.CharField(max_length=200, verbose_name='标题中文')),
                ('keyword', models.CharField(max_length=200, verbose_name='产品关键字')),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='采购价格')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='销售价格')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='颜色')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='尺寸')),
                ('style', models.CharField(blank=True, max_length=100, null=True, verbose_name='风格')),
                ('amount', models.PositiveIntegerField(verbose_name='数量')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='材质')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='产品描述')),
                ('trans_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='运输')),
                ('trans_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='运费')),
                ('pic_main', models.ImageField(upload_to='images', verbose_name='主图')),
                ('pic_1st', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片1')),
                ('pic_2nd', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片2')),
                ('pic_3rd', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片3')),
                ('pic_4th', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片4')),
                ('pic_5th', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片5')),
                ('pic_6th', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片6')),
                ('pic_7th', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片7')),
                ('pic_8th', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片8')),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='产品重量(克)')),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='包装重量(克)')),
                ('product_length', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='产品长(cm)')),
                ('product_width', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='产品宽(cm)')),
                ('product_high', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='产品高(cm)')),
                ('product_link_1688', models.CharField(max_length=200, verbose_name='产品1688链接')),
                ('product_link_ebay', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品ebay链接')),
                ('product_link_amazon', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品Amazon链接')),
                ('product_link_speed_sell', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品速卖链接')),
                ('product_remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='io_tool.Catalog', verbose_name='类别')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='开发人员')),
            ],
        ),
    ]
