# Generated by Django 2.2.5 on 2019-09-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_tool', '0003_auto_20190830_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.CharField(max_length=500, verbose_name='产品关键字'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link_1688',
            field=models.CharField(max_length=1400, verbose_name='产品1688链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link_amazon',
            field=models.CharField(blank=True, max_length=1400, null=True, verbose_name='产品Amazon链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link_ebay',
            field=models.CharField(blank=True, max_length=1400, null=True, verbose_name='产品ebay链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link_speed_sell',
            field=models.CharField(blank=True, max_length=1400, null=True, verbose_name='产品速卖链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='风格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_cn',
            field=models.CharField(max_length=500, verbose_name='标题中文'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=500, verbose_name='标题英文'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trans_method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='运输'),
        ),
    ]
