# Generated by Django 2.2.5 on 2019-09-26 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('io_tool', '0004_auto_20190919_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewer_1st',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_products', to=settings.AUTH_USER_MODEL, verbose_name='一审人'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewer_final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_products', to=settings.AUTH_USER_MODEL, verbose_name='终审人'),
        ),
    ]
